name: 'xkcd_analytics_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  xkcd_analytics_project:
    +schema: "{{ env_var('DBT_ANALYTICS_SCHEMA', 'ANALYTICS') }}"
    +materialized: table  # Default materialization for all models